apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-bestsell-app
  namespace: ia-bestsell
  labels:
    app: ia-bestsell-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ia-bestsell-app
  template:
    metadata:
      labels:
        app: ia-bestsell-app
    spec:
      containers:
        - name: ia-bestsell-app
          image: 433806445659.dkr.ecr.eu-west-2.amazonaws.com/grip-platform-dev-app:latest
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20